{% set name = "nvidia-apex" %}
{% set version = "0.1" %}
{% set commit = "088985936518be7e25795a30d8ab33affa9db6ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/apex/archive/{{ commit }}.tar.gz
  sha256: cc5ce27aa30b5ade54d520fafc1cd7d293dfba58c51851759a034d03e3f370bb

build:
  number: 0
  string: cuda{{ cudatoolkit | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [variant == "gpu"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [variant == "cpu"]
  skip: True  # [osx or py2k or (win and vc<14)]

outputs:
  - name: nvidia-apex-proc
    version: {{ version }}
    build:
      number: 0
      string: {{ variant }}
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/nvidia-apex-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU nvidia-apex build.

  - name: nvidia-apex
    version: {{ version }}
    build:
      number: 1
      script: python -m pip install . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pytorch
        - setuptools
        - pip
        - cudatoolkit {{ cudatoolkit }}*  # [variant == "gpu"]
        # might not need this
        - cudnn {{ cudnn }}*              # [variant == "gpu"]
      run:
        - python
        - pytorch
        - cxxfilt  # [linux]
        - tqdm
        - numpy
        - PyYAML
        - pytest
      run_constrained:
        - nvidia-apex-proc * {{ variant }}
    test:
      imports:
        - apex
        - apex.amp
        - apex.parallel
        - apex.optimizers
        - apex.normalization.fused_layer_norm
    about:
      home: "https://nvidia.github.io/apex/"
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: "a Pytorch extension with NVIDIA-maintained utilities to streamline mixed precision and distributed training."
      doc_url: "https://nvidia.github.io/apex/"
      dev_url: "https://github.com/NVIDIA/apex"

about:
  home: "https://nvidia.github.io/apex/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "a Pytorch extension with NVIDIA-maintained utilities to streamline mixed precision and distributed training."
  doc_url: "https://nvidia.github.io/apex/"
  dev_url: "https://github.com/NVIDIA/apex"

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - jakirkham
    - rluria14
