c_compiler_version:
    - 7.3                # [linux]
cxx_compiler_version:
    - 7.3                # [linux]
cudatoolkit:
    - 10.2
cudnn:
    - 7.6
openblas:
    - 0.3.3
mkl:
    - 2019
numpy:
    - 1.11
python:
    - 3.6
variant:
    - gpu      